apply plugin: 'com.android.library'


android {
    compileSdk 35
    
    defaultConfig {
        minSdk 26
        targetSdk 35
        buildToolsVersion = '35.0.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    namespace 'com.github.mikephil.charting'
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    testImplementation 'junit:junit:4.13.2'
}