-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgM4HL/JIizqZqpT+D
GZyK6s6UIFKNWZ16J0aLWzLQjD6gCgYIKoZIzj0DAQehRANCAATqVCurlH9B2VJ0
bOEUZFru6YLpUheqVhLFSdNhasTso9TRgk9Gqt6DbzbFz33XmdkXpXBZQydD9X/m
BNW5v4O+
-----END PRIVATE KEY-----