<?php
session_start();
if(isset($_SESSION["start_report_admin"])){
unset($_SESSION["start_report_admin"]);
unset($_SESSION["start_report_admin_name"]);
unset($_SESSION["start_user_type"]);
unset($_SESSION["order_show_branch"]);
header("location:index.php");
}else{
header("location:index.php");
}
?>