let DataStorage = {
    auth_token:'',

    typeOfUse: '',
    primaryColorCode: '',
    gradientColorCode: [],
    transColorCode: '',
    menuColorCode: '',
    emp_name: '',
    emp_mobile_number: '',
    device_id: '',
    password: '',
    sale_access: '',
    isDataTableDownloaded: '0',
    web_link: '',
    feedback_customer_name: '',
    feedback_customer_id: '',
    feedback_visit_date: '',
    select_type_of_option: '',
    productQtyAddedList: [],
    shipTo: '',
    dealer_sub_dealer_id: '',
    consignee_name: '',
    consignee_address: '',
    consignee_phone_number: '',
    destination_address: '',
    destination_address_code: '',
    destination_address_type: '',
    ship_item: {},
    dump_obj: {},
    freight: '',
    for_type: '',
    delivery_remarks: '',
    dealer_truck: '',
    plant_name: '',
    popProductList: [],
    isFirstOpen: true,
    isBoriMenuShow: false,
    web_page_title: '',
    isSbsRegister: false,
    isCementRegister: false,
    image_url: '',

    ageingObj:{},
    dayWiseAgeingList:[],
    type:''
}
export default DataStorage